[build-system]
build-backend = "mesonpy"
requires = [
    "meson-python>=0.15",
    "meson>=1.2.3",
    "ninja",
]

[project]
name = "wrouter"
version = "1.0.1"
description = "Fast and deterministric symbolic Web URL route resolver."
authors = [
  { name="Damien Bezborodov", email="dbezborodov@gmail.com" },
]
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: C",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Libraries",
]

[project.urls]
"Homepage" = "https://github.com/bezborodow/libwrouter"
"Bug Tracker" = "https://github.com/bezborodow/libwrouter/issues"

[tool.meson-python.args]
setup = ["-Dpython_package=true"]
