executable(
    'hello_cpp',
    'hello.cpp',

    dependencies: wrouter_cpp_dep,
)

executable(
    'callback_cpp',
    'callback.cpp',

    dependencies: wrouter_cpp_dep,
)

executable(
    'no_context_cpp',
    'no_context.cpp',

    dependencies: wrouter_cpp_dep,
)

executable(
    'resolve_lambda_cpp',
    'resolve_lambda.cpp',

    dependencies: wrouter_cpp_dep,
)
